version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: mi_postgres
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass123
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
